title:              Beauhomme
email:              beauhomme@gmail.com
description:        Data Portfolio
author:             beauhomme
baseurl:            ""
url:                "https://beauhomme.github.io"

# Social Profiles
twitter_username:   dawn
github_username:    beauhomme
facebook_username:  dawn
instagram_username:  dawn
linkedin_username:  dawn

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
